# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_extendeduser_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extendeduser',
            old_name='nombre',
            new_name='name',
        ),
    ]
