# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20151211_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField()),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ExtendedUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill_user',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_select',
        ),
        migrations.DeleteModel(
            name='Skill_User',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='skills',
            field=models.ManyToManyField(through='users.SkillUser', to='users.Skill'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
