# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20151211_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilluser',
            name='percentage',
            field=models.TextField(),
        ),
    ]
