# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20151211_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilluser',
            old_name='percentage',
            new_name='experience',
        ),
    ]
