# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20151211_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilluser',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
