# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 02:35
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', django_markdown.models.MarkdownField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'title', unique=True)),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
